version: '3'
services:
  api:
    build: .
    ports:
      - "8080:80" # Maps port 8080 on the host to port 80 on the container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: 
      - db # This line ensures that db service is started before the API
    volumes:
      - .:/app
    command: ["dotnet", "ClinicalTrialAPI.Api.dll"]

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" # Maps port 1433 on the host to port 1433 on the container
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
